import Head from 'next/head';
import React from 'react'
import { Header } from './Header';

const layout = ({ children }) => {
  return (
    <>
      <Head>
        <title>Recent Editions</title>
        <meta
          name='description'
          content='Generated by create next app'
        />
        <link
          rel='icon'
          type='image/png'
          sizes='32x32'
          href='/assets/favicon-32x32.png'
        />
      </Head>
      <Header />
      <main>
        {children}
      </main>
    </>
  )
}

export default layout
