import { Box } from '@zoralabs/zord'
import Head from 'next/head';
import React from 'react'
import { Header } from './Header';

const layout = ({ children }) => {
  return (
    <>
      <Head>
        <title>Recent Editions</title>
        <meta
          name='description'
          content='Generated by create next app'
        />
        <link
          rel='icon'
          type='image/png'
          sizes='32x32'
          href='/assets/favicon-32x32.png'
        />
        {/* <!-- Google tag (gtag.js) --> */}
        {/* <Script
          async
          src={`https://www.googletagmanager.com/gtag/js?id=${process.env.NEXT_PUBLIC_GA_TRACKING_ID}`}
        ></Script> */}
        {/* <Script
          dangerouslySetInnerHTML={{
            __html: `
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());

            gtag('config', '${process.env.NEXT_PUBLIC_GA_TRACKING_ID}', {
              page_path: window.location.pathname,
            });
            `,
          }}
        /> */}
      </Head>
      <Header />
      <main>
        {children}
      </main>
    </>
  )
}

export default layout
