import type { NextPage } from 'next';
import { Feed } from '../components/Feed';
import { Header } from '../components/Header';

import Head from 'next/head';
import Image from 'next/image';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Recent Editions</title>
        <meta
          name='description'
          content='Generated by create next app'
        />
        <link
          rel='icon'
          type='image/png'
          sizes='32x32'
          href='/favicon-32x32.png'
        />
        <style>
          {/* @import */}
          url('https://fonts.googleapis.com/css2?family=Inter:wght@400;600&display=swap');
        </style>
      </Head>
      <Header />
      <Feed />
    </div>
  );
};

export default Home;
